
spring:
  application:
    name: "stock_exchanger"
  r2dbc:
    url: ${R2DB_URL:r2dbc:postgresql://localhost:5432/public}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/public}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
